# Site settings
title: Kaan Sadık Karadağ's Blog
description: 'Application Security Engineer @ Kuehne+Nagel.<br />Currently Living in Tallinn/Estonia.<br />A Cyber Security enthusiast, Computer Engineering BSc. holder, regularly participates in CTFs. Currently putting an epic battle with Cyber Security MSc. thesis.'
baseurl: ''
google_analytics: 'UA-113548627-1'
disqus_shortname: 'kaansk'
URL: 'kaansk.github.io'

author:
  name: 'Kaan Sadık Karadağ'
  email: kaansk@gmail.com
  twitter_username: KaanSKaradag
  facebook_username: kaansk
  github_username:  kaansk
  linkedin_username:  kaansk
  pgpkey: 'https://pgp.mit.edu/pks/lookup?op=get&search=0xEE2DF9C09F2DB8D4'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate','jekyll-seo-tag']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
include: ['.well-known', 'robots.txt']