baseURL: 'https://kaankaradag.com'
defaultContentLanguage: en
theme: LoveIt

#themesDir: ../..
title: Kaan S. Karadag's Blog
enableRobotsTXT: true
#enableGitInfo: true
enableEmoji: true
languages:
  en:
    weight: 1
    languageCode: en
    languageName: English
    hasCJKLanguage: false
    paginate: 12
    googleAnalytics: 'G-H73XGNYQ58'
    #copyright: >-
    #  This work is licensed under a Creative Commons Attribution-NonCommercial
    #  4.0 International License.
    menu:
      main:
        - identifier: posts
          pre: ''
          post: ''
          name: Posts
          url: /posts/
          title: ''
          weight: 1
        - identifier: tags
          pre: ''
          post: ''
          name: Tags
          url: /tags/
          title: ''
          weight: 2
        - identifier: categories
          pre: ''
          post: ''
          name: Categories
          url: /categories/
          title: ''
          weight: 3
        #- identifier: about
        #  pre: ''
        #  post: ''
        #  name: About
        #  url: /about/
        #  title: ''
        #  weight: 4
    params:
      home:
        rss: 10
        profile:
          enable: true
          gravatarEmail: ''
          avatarURL: /images/avatar.png
          title: "Kaan S. Karadag"
          subtitle: 'Cyber Security Engineer | Incident Response | Computer Engineering BSc. | CEH Master'
          typeit: true
          social: true
          disclaimer: ''
        posts:
          enable: true
          paginate: 6
      social:
        GitHub: kaansk
        Linkedin: kaansk
        Twitter: ''
        Instagram: ''
        Facebook: ''
        Telegram: ''
        Medium: ''
        Gitlab: ''
        Youtubelegacy: ''
        Youtubecustom: ''
        Youtubechannel: ''
        Tumblr: ''
        Quora: ''
        Keybase: ''
        Pinterest: ''
        Reddit: ''
        Codepen: ''
        FreeCodeCamp: ''
        Bitbucket: ''
        Stackoverflow: ''
        Weibo: ''
        Odnoklassniki: ''
        VK: ''
        Flickr: ''
        Xing: ''
        Snapchat: ''
        Soundcloud: ''
        Spotify: ''
        Bandcamp: ''
        Paypal: ''
        Fivehundredpx: ''
        Mix: ''
        Goodreads: ''
        Lastfm: ''
        Foursquare: ''
        Hackernews: ''
        Kickstarter: ''
        Patreon: ''
        Steam: ''
        Twitch: ''
        Strava: ''
        Skype: ''
        Whatsapp: ''
        Zhihu: ''
        Douban: ''
        Angellist: ''
        Slidershare: ''
        Jsfiddle: ''
        Deviantart: ''
        Behance: ''
        Dribbble: ''
        Wordpress: ''
        Vine: ''
        Googlescholar: ''
        Researchgate: ''
        Thingiverse: ''
        Devto: ''
        Gitea: ''
        XMPP: ''
        Matrix: ''
        Bilibili: ''
        Email: info@kaankaradag.com
        RSS: true
        pgp: https://pgp.circl.lu/pks/lookup?op=get&search=0xC87A8F9F5B2F03CB
        #Mastodon: false
        #  id: ''
        #  prefix: ''
params:
  version: 0.2.X
  defaultTheme: dark
  gitRepo: ''
  fingerprint: ''
  dateFormat: '2006-01-02'
  images:
    - /logo.png
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: ''
      name: Home
      #pre: <i class='far fa-kiss-wink-heart fa-fw'></i>
      post: ''
      typeit: false
  footer:
    enable: true
    custom: ''
    hugo: false
    copyright: false
    author: true
    since: 2018
    icp: ''
    #license: >-
    #  <a rel="license external nofollow noopener noreffer"
    #  href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC
    #  BY-NC 4.0</a>
  section:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  list:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  page:
    hiddenFromHomePage: false
    hiddenFromSearch: false
    twemoji: false
    lightgallery: false
    ruby: true
    fraction: true
    fontawesome: true
    linkToMarkdown: true
    rssFullText: false
    toc:
      enable: true
      keepStatic: false
      auto: true
    code:
      copy: true
      maxShownLines: 10
    math:
      enable: false
      blockLeftDelimiter: ''
      blockRightDelimiter: ''
      inlineLeftDelimiter: ''
      inlineRightDelimiter: ''
      copyTex: true
      mhchem: true
    share:
      enable: true
      Twitter: true
      Facebook: true
      Linkedin: true
      Whatsapp: false
      Pinterest: false
      Tumblr: false
      HackerNews: true
      Reddit: false
      VK: false
      Buffer: false
      Xing: false
      Line: true
      Instapaper: false
      Pocket: false
      Digg: false
      Stumbleupon: false
      Flipboard: false
      Weibo: false
      Renren: false
      Myspace: false
      Blogger: false
      Baidu: false
      Odnoklassniki: false
      Evernote: false
      Skype: false
      Trello: false
      Mix: false
    comment:
      enable: true
      disqus:
        enable: false
        shortname: ''
      gitalk:
        enable: false
        owner: ''
        repo: ''
        clientId: ''
        clientSecret: ''
      valine:
        enable: false
        appId: ''
        appKey: ''
        placeholder: ''
        avatar: mp
        meta: ''
        pageSize: 10
        lang: ''
        visitor: true
        recordIP: true
        highlight: true
        enableQQ: false
        serverURLs: ''
        emoji: ''
      facebook:
        enable: false
        width: 100%
        numPosts: 10
        appId: ''
        languageCode: ''
      telegram:
        enable: false
        siteID: ''
        limit: 5
        height: ''
        color: ''
        colorful: true
        dislikes: false
        outlined: false
      commento:
        enable: false
      utterances:
        enable: false
        repo: ''
        issueTerm: pathname
        label: ''
        lightTheme: github-light
        darkTheme: github-dark
    library:
      css: {}
      js: {}
    seo:
      images: []
      publisher:
        name: Kaan S. Karadag
        logoUrl: /images/avatar.png
  typeit:
    speed: 100
    cursorSpeed: 1000
    cursorChar: '|'
    duration: -1
  verification:
    google: ''
    bing: ''
    yandex: ''
    pinterest: ''
    baidu: ''
  seo:
    image: /images/Apple-Devices-Preview.png
    thumbnailUrl: /images/screenshot.png
  analytics:
    enable: true
    google:
      id: 'G-H73XGNYQ58'
      anonymizeIP: true
    fathom:
      id: ''
      server: ''
  cookieconsent:
    enable: false
    content:
      message: ''
      dismiss: ''
      link: ''
  cdn:
    data: jsdelivr.yml
  compatibility:
    polyfill: false
    objectFit: false
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
author:
  name: Kaan S. Karadag
  email: 'info@kaankaradag.com'
  link: ''
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: ':filename'
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
